apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc #Name that we referred into deployment file
spec:
  volumeName: nginx-pv
  storageClassName: local-storage-example #A claim can request a particular class by specifying the name of a StorageClass using the attribute storageClassName. Only PVs of the requested class, ones with the same storageClassName as the PVC, can be bound to the PVC.
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi