apiVersion: v1
kind: Pod
metadata:
  name: bnb-frontend-pod
  namespace: demo
  labels:
    env: bnb-test
spec:
  restartPolicy: OnFailure
  containers:
  - name: bnb-frontend-ctr
    imagePullPolicy: Always
    image: kaiwalyakoparkar/test-client:1.0
    ports:
    - containerPort: 3000
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "1000m"

---

