apiVersion: apps/v1
kind: Deployment
metadata:
  name: bnb-frontend-deploy
  labels:
    app: bnb-frontend-deploy
  namespace: demo
spec:
  ## Set to 5 for start of lab
  replicas: 5
  selector:
    matchLabels:
      env: bnb-test
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        env: bnb-test
    spec:
      containers:
      - name: bnb-frontend-ctr
        image: kaiwalyakoparkar/test-client:1.0
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: bnb-frontend-deploy
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: bnb-frontend-deploy
  ports:
  - port: 3000
    targetPort: 3000
