apiVersion: apps/v1
kind: Deployment
metadata:
  name: bnb-backend-deploy
  labels:
    app: bnb-backend-deploy
  namespace: demo
spec:
  ## Set to 5 for start of lab
  replicas: 5
  selector:
    matchLabels:
      env: bnb-test
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        env: bnb-test
    spec:
      containers:
      - name: bnb-backend-ctr
        image: kaiwalyakoparkar/test-server:1.0
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: bnb-backend-deploy
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: bnb-backend-deploy
  ports:
  - port: 5000
    targetPort: 5000