apiVersion: v1
kind: Service
metadata:
  name: bnb-lb
  namespace: demo
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 3000
  selector:
    env: bnb-test
    app: bnb-frontend-deploy
